name: Fastboat
version: 0.0.1-BETA
main: com.koningcool.fastboat.fastboat.Fastboat
api-version: 1.19
authors: [ koningcool ]
description: Make boats faster!
commands:
  setboatspeed:
    description: Use this command to set the speed of boats.
    aliases: sbs

  boatspeed:
    description: Use this command to get the current boat speed.
    aliases:
      - bspeed
      - bs

